java:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - 1.2
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - 3.9
build:
  - script: |
      git clone -b feature/76 --single-branch "https://github.com/tolbertam/scassandra-server.git"
      cd scassandra-server
      ./gradlew assemble install -x signArchives
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Plong
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      scassandra.version=1.1.0-SNAPSHOT
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
      scassandra.version=1.1.0-SNAPSHOT
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
